version: "3.9"

services:
  flowgo:
    image: tuhinsu/apiflow:latest
    container_name: flowgo
    restart: unless-stopped

    volumes:
      - ./config.json:/app/config.json:ro

    environment:
      - TZ=Asia/Kolkata